name: safe_value_notifier
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/camrongiuliani/safe_value_notifier

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  safe_change_notifier: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: